name: Terraform
env:
  project_id: db-cicdpipeline-wave-3
on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  get-secret:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GIT_HUB__CICD_PROVIDE }}
          service_account: ${{ secrets.garage_service_account }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2
 
      - name: Run terraform init
        run: |
          terraform init
      - name: Run terraform plan -destroy
        run: |
          terraform plan
      - name: Run terraform apply
        run: |
          terraform apply -auto-approve
          terafrom destory -target google_kms_key_ring.kms_key_ring_wave3
          
