# This is a basic workflow that is manually triggered

name: Manual workflow to authenticate google cloud
on: 
  workflow_dispatch
  # Inputs the workflow accepts.
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-secret:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GIT_HUB__CICD_PROVIDE }}
          service_account: ${{ secrets.garage_service_account }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Install expect
        run: sudo apt-get install -y expect
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2
      
      - name: Run terraform init
        run: |
            export TF_LOG=DEBUG
            expect <<- DONE
            spawn terraform init -migrate-state -lock=false
            expect "Enter a value:"
            send "yes\r"
            expect eof
            DONE
      - name: Run terraform plan -destroy
        if: github.ref == 'refs/heads/main'
        run: |
          terraform plan